changelog:
  categories:
    - title: Features
      labels:
        - enhancement
        - feature
        - feat
    - title: Bug Fixes
      labels:
        - bug
        - bugfix
        - fix
    - title: Performance
      labels:
        - performance
        - perf
    - title: Documentation
      labels:
        - documentation
        - docs
    - title: Maintenance
      labels:
        - chore
        - dependencies
        - refactor
        - build
        - ci
    - title: Other Changes
      labels:
        - '*'
