import { randomUUID } from "node:crypto";
import { isLocalPostgres } from "../../lib/config.js";
import { hashPassword } from "../../lib/desktop-auth.js";
import { prisma } from "../../lib/prisma.js";
import { checkSelfHostInstanceLicense, getStoredInstanceLicense, LicenseClientError, verifyStoredInstanceLicense, type VerifiedEntitlement } from "../../lib/license-client.js";
import { isProvisionedMembership, isProvisionedTeam, membershipProvisioningSignature, teamProvisioningSignature } from "../../lib/team-provisioning.js";

const messages: Record<string, string> = { SELF_HOST_ONLY: "Teams are available only on a self-hosted server.", SUPER_ADMIN_REQUIRED: "Only the SuperAdmin can manage Teams.", TEAM_NAME_TAKEN: "A Team with this name already exists.", TEAM_LIMIT_REACHED: "This installation has reached its Team limit.", MEMBER_LIMIT_REACHED: "This installation has reached its active member limit.", MEMBER_ALREADY_EXISTS: "This person is already a member of this Team.", MEMBER_ALREADY_ASSIGNED: "This person is already assigned to another Team.", USER_NOT_FOUND: "No account was found with that email address.", SUPER_ADMIN_CANNOT_BE_MEMBER: "A SuperAdmin cannot be added as a Team member.", MEMBER_INACTIVE: "Your Team membership is inactive. Contact the SuperAdmin to restore access.", TEAM_INTEGRITY_UNAVAILABLE: "This Team is unavailable because its membership records could not be verified. Contact the SuperAdmin." };
export class TeamServiceError extends Error { constructor(public readonly code: string, public readonly status: number, message = messages[code] || "We couldn't complete this Team request.") { super(message); this.name = "TeamServiceError"; } }
const database = () => { if (!isLocalPostgres() || !prisma) throw new TeamServiceError("SELF_HOST_ONLY", 404); return prisma as any; };
const admin = (value: boolean) => { if (!value) throw new TeamServiceError("SUPER_ADMIN_REQUIRED", 403); };

async function usage() { const db = database(); const [teamCount, memberCount] = await Promise.all([db.team.count({ where: { type: { not: "personal" }, status: "active" } }), db.teamMember.count({ where: { status: "active" } })]); return { teamCount, memberCount }; }
async function entitlement(): Promise<VerifiedEntitlement> {
  try { const state = getStoredInstanceLicense(); if (!state) throw new LicenseClientError("LICENSE_NOT_ACTIVATED", 409); if (Date.now() - Date.parse(state.lastCheckedAt) < 900_000) return verifyStoredInstanceLicense().entitlement; return (await checkSelfHostInstanceLicense(await usage())).entitlement; }
  catch (error) { if (error instanceof LicenseClientError && ["LICENSE_SERVICE_UNAVAILABLE", "SERVICE_UNAVAILABLE"].includes(error.code)) return verifyStoredInstanceLicense().entitlement; if (error instanceof LicenseClientError) throw new TeamServiceError(error.code, error.status); throw error; }
}
function license() { try { const { state, entitlement: value } = verifyStoredInstanceLicense(); return { valid: true, status: "active", id: value.licenseId, codeLastFour: state.codeLastFour, planCode: value.planCode, expiresAt: new Date(value.expiresAt * 1000), maxMembers: value.maxMembers, maxTeams: value.maxTeams, bindingGeneration: value.bindingGeneration, lastCheckedAt: state.lastCheckedAt }; } catch (error) { return { valid: false, status: "unavailable", errorCode: error instanceof LicenseClientError ? error.code : "LICENSE_STATE_INVALID" }; } }
function response(team: any, canManage: boolean) { const members = Array.isArray(team.members) ? team.members.map((m: any) => ({ id: m.user?.id || m.userId, email: m.user?.email || null, name: m.user?.name || null, role: "member", status: m.status, joinedAt: m.joinedAt })) : undefined; return { id: team.id, name: team.name, members, memberCount: members ? members.filter((m: any) => m.status === "active").length : team._count?.members ?? 0, canManage, license: license() }; }
async function team(id: string, userId: string, superAdmin: boolean) { const db = database(); if (!superAdmin && !(await db.teamMember.findFirst({ where: { teamId: id, userId, status: "active" } }))) return null; const value = await db.team.findUnique({ where: { id }, include: { _count: { select: { members: { where: { status: "active" } } } }, members: { include: { user: { select: { id: true, email: true, name: true } } } } } }); return value?.type === "personal" ? null : value; }
async function integrity(value: any) { if (!isProvisionedTeam(value)) throw new TeamServiceError("TEAM_INTEGRITY_UNAVAILABLE", 403); const members = value.members || await database().teamMember.findMany({ where: { teamId: value.id } }); if (members.filter((m: any) => m.status === "active").some((m: any) => !isProvisionedMembership(m))) throw new TeamServiceError("TEAM_INTEGRITY_UNAVAILABLE", 403); const valueEntitlement = await entitlement(); const current = await usage(); if ((valueEntitlement.maxTeams !== null && current.teamCount > valueEntitlement.maxTeams) || (valueEntitlement.maxMembers !== null && current.memberCount > valueEntitlement.maxMembers)) throw new TeamServiceError("TEAM_INTEGRITY_UNAVAILABLE", 403); return valueEntitlement; }
export async function canAccessTeam(id: string, userId: string, superAdmin: boolean) { try { const value = await team(id, userId, superAdmin); if (!value || value.status !== "active") return false; await integrity(value); return true; } catch { return false; } }
export async function listTeams(userId: string, superAdmin: boolean) { const db = database(); const values = superAdmin ? await db.team.findMany({ include: { _count: { select: { members: { where: { status: "active" } } } }, members: true } }) : (await db.teamMember.findMany({ where: { userId, status: "active" }, include: { team: { include: { _count: { select: { members: { where: { status: "active" } } } }, members: true } } } })).map((m: any) => m.team); const output = await Promise.all(values.filter((v: any) => v.type !== "personal").map(async (v: any) => { try { await integrity(v); return response(v, superAdmin); } catch (error) { return superAdmin && error instanceof TeamServiceError && error.code === "TEAM_INTEGRITY_UNAVAILABLE" ? { ...response(v, true), integrity: { available: false, code: error.code } } : null; } })); return output.filter(Boolean); }
export async function getTeam(id: string, userId: string, superAdmin: boolean) { admin(superAdmin); const value = await team(id, userId, true); return value ? response(value, true) : null; }
export async function createTeam(data: { name: string; userId: string; isSuperAdmin: boolean }) { admin(data.isSuperAdmin); const db = database(); const name = data.name.trim(); if (await db.team.findFirst({ where: { name: { equals: name, mode: "insensitive" } } })) throw new TeamServiceError("TEAM_NAME_TAKEN", 409); const value = await entitlement(); const current = await usage(); if (value.maxTeams !== null && current.teamCount >= value.maxTeams) throw new TeamServiceError("TEAM_LIMIT_REACHED", 409); const id = randomUUID(); const createdAt = new Date(); const created = await db.team.create({ data: { id, name, type: "team", createdBy: data.userId, status: "active", createdAt, provisioningSignature: teamProvisioningSignature({ id, status: "active", createdAt }) } }); return response(created, true); }
export async function refreshTeamLicense(_id: string, _userId: string, superAdmin: boolean) { admin(superAdmin); await checkSelfHostInstanceLicense(await usage()); return null; }
export async function addMember(teamId: string, email: string, superAdmin: boolean, account: { name?: string; password?: string } = {}) { admin(superAdmin); const db = database(); const value = await team(teamId, "", true); if (!value) return null; const plan = await integrity(value); let user = await db.user.findUnique({ where: { email: email.trim().toLowerCase() } }); if (!user && (!account.name || !account.password)) throw new TeamServiceError("USER_NOT_FOUND", 404); if (user?.isSuperAdmin) throw new TeamServiceError("SUPER_ADMIN_CANNOT_BE_MEMBER", 409); const current = await usage(); if (plan.maxMembers !== null && current.memberCount >= plan.maxMembers) throw new TeamServiceError("MEMBER_LIMIT_REACHED", 409); user = user || await db.user.create({ data: { email: email.trim().toLowerCase(), name: account.name!.trim(), password: hashPassword(account.password!), isSuperAdmin: false } }); const active = await db.teamMember.findFirst({ where: { userId: user.id, status: "active" } }); if (active) throw new TeamServiceError(active.teamId === teamId ? "MEMBER_ALREADY_EXISTS" : "MEMBER_ALREADY_ASSIGNED", 409); const existing = await db.teamMember.findFirst({ where: { teamId, userId: user.id } }); const id = existing?.id || randomUUID(); const joinedAt = new Date(); const provisioningSignature = membershipProvisioningSignature({ id, teamId, userId: user.id, status: "active", joinedAt }); await db.teamMember.upsert({ where: { teamId_userId: { teamId, userId: user.id } }, create: { id, teamId, userId: user.id, role: "member", status: "active", joinedAt, provisioningSignature }, update: { status: "active", joinedAt, provisioningSignature } }); return getTeam(teamId, user.id, true); }
export async function removeMember(teamId: string, userId: string, superAdmin: boolean) { admin(superAdmin); const db = database(); const member = await db.teamMember.findFirst({ where: { teamId, userId, status: "active" } }); if (!member) return false; await db.teamMember.update({ where: { id: member.id }, data: { status: "inactive", provisioningSignature: membershipProvisioningSignature({ ...member, status: "inactive" }) } }); await db.session.deleteMany({ where: { userId } }); return true; }
export async function canUserLogin(userId: string): Promise<{ allowed: true; teamId?: string } | { allowed: false; code: string }> { if (!isLocalPostgres() || !prisma) return { allowed: true }; const memberships = await (prisma as any).teamMember.findMany({ where: { userId, status: "active" } }); if (!memberships.length) return { allowed: true }; for (const membership of memberships) { const value = await team(membership.teamId, userId, false); try { if (value) { await integrity(value); return { allowed: true, teamId: membership.teamId }; } } catch (error) { if (error instanceof TeamServiceError && error.code === "TEAM_INTEGRITY_UNAVAILABLE") return { allowed: false, code: error.code }; } } return { allowed: false, code: "LICENSE_EXPIRED_OR_INVALID" }; }
