import { randomUUID } from "node:crypto";

import { isLocalPostgres } from "../../lib/config.js";
import { hashPassword } from "../../lib/desktop-auth.js";
import { checkSelfHostInstanceLicense, getStoredInstanceLicense, LicenseClientError, verifyStoredInstanceLicense, type VerifiedEntitlement } from "../../lib/license-client.js";
import { prisma } from "../../lib/prisma.js";
import { isProvisionedMembership, isProvisionedTeam, membershipProvisioningSignature, teamProvisioningSignature } from "../../lib/team-provisioning.js";

export const TEAM_ROLES = ["manager", "staff"] as const;
export type TeamRole = (typeof TEAM_ROLES)[number];

const messages: Record<string, string> = {
  SELF_HOST_ONLY: "Teams are available only on a self-hosted server.", SUPER_ADMIN_REQUIRED: "Only the SuperAdmin can create Teams.", TEAM_MANAGER_REQUIRED: "Only a Team Manager can manage this Team.", TEAM_NAME_TAKEN: "A Team with this name already exists.", TEAM_LIMIT_REACHED: "This installation has reached its Team limit.", MEMBER_LIMIT_REACHED: "This installation has reached its active member limit.", MEMBER_ALREADY_EXISTS: "This person is already a member of this Team.", MEMBER_ALREADY_ASSIGNED: "This person is already assigned to another Team.", USER_NOT_FOUND: "No account was found with that email address.", SUPER_ADMIN_CANNOT_BE_MEMBER: "A SuperAdmin cannot be added as a Team member.", LAST_MANAGER_REQUIRED: "A Team must retain at least one Manager.", MEMBER_INACTIVE: "Your Team membership is inactive. Contact the SuperAdmin to restore access.", TEAM_INTEGRITY_UNAVAILABLE: "This Team is unavailable because its membership records could not be verified. Contact the SuperAdmin.",
};
export class TeamServiceError extends Error { constructor(public readonly code: string, public readonly status: number, message = messages[code] || "We couldn't complete this Team request.") { super(message); this.name = "TeamServiceError"; } }
const database = () => { if (!isLocalPostgres() || !prisma) throw new TeamServiceError("SELF_HOST_ONLY", 404); return prisma as any; };
const admin = (value: boolean) => { if (!value) throw new TeamServiceError("SUPER_ADMIN_REQUIRED", 403); };
export const isTeamRole = (value: unknown): value is TeamRole => typeof value === "string" && (TEAM_ROLES as readonly string[]).includes(value);

async function usage() { const db = database(); const [teamCount, memberCount] = await Promise.all([db.team.count({ where: { type: { not: "personal" }, status: "active" } }), db.teamMember.count({ where: { status: "active" } })]); return { teamCount, memberCount }; }
async function entitlement(): Promise<VerifiedEntitlement> {
  try { const state = getStoredInstanceLicense(); if (!state) throw new LicenseClientError("LICENSE_NOT_ACTIVATED", 409); if (Date.now() - Date.parse(state.lastCheckedAt) < 900_000) return verifyStoredInstanceLicense().entitlement; return (await checkSelfHostInstanceLicense(await usage())).entitlement; }
  catch (error) { if (error instanceof LicenseClientError && ["LICENSE_SERVICE_UNAVAILABLE", "SERVICE_UNAVAILABLE"].includes(error.code)) return verifyStoredInstanceLicense().entitlement; if (error instanceof LicenseClientError) throw new TeamServiceError(error.code, error.status); throw error; }
}
function response(team: any, canManage: boolean) { const members = Array.isArray(team.members) ? team.members.map((member: any) => ({ id: member.user?.id || member.userId, email: member.user?.email || null, name: member.user?.name || null, role: isTeamRole(member.role) ? member.role : "staff", status: member.status, joinedAt: member.joinedAt })) : undefined; return { id: team.id, name: team.name, members, memberCount: members ? members.filter(member => member.status === "active").length : team._count?.members ?? 0, canManage }; }
function teamInclude() { return { _count: { select: { members: { where: { status: "active" } } } }, members: { include: { user: { select: { id: true, email: true, name: true } } } } }; }
async function team(id: string, userId: string, superAdmin: boolean) { const db = database(); if (!superAdmin && !(await db.teamMember.findFirst({ where: { teamId: id, userId, status: "active" } }))) return null; const value = await db.team.findUnique({ where: { id }, include: teamInclude() }); return value?.type === "personal" ? null : value; }
async function integrity(value: any) { if (!isProvisionedTeam(value)) throw new TeamServiceError("TEAM_INTEGRITY_UNAVAILABLE", 403); const members = value.members || await database().teamMember.findMany({ where: { teamId: value.id } }); if (members.filter((member: any) => member.status === "active").some((member: any) => !isProvisionedMembership(member))) throw new TeamServiceError("TEAM_INTEGRITY_UNAVAILABLE", 403); const valueEntitlement = await entitlement(); const current = await usage(); if ((valueEntitlement.maxTeams !== null && current.teamCount > valueEntitlement.maxTeams) || (valueEntitlement.maxMembers !== null && current.memberCount > valueEntitlement.maxMembers)) throw new TeamServiceError("TEAM_INTEGRITY_UNAVAILABLE", 403); return valueEntitlement; }

export async function canManageTeam(teamId: string, userId: string, superAdmin?: boolean) { const db = database(); const isSuperAdmin = superAdmin ?? Boolean((await db.user.findUnique({ where: { id: userId }, select: { isSuperAdmin: true } }))?.isSuperAdmin); if (isSuperAdmin) return true; return (await db.teamMember.findFirst({ where: { teamId, userId, status: "active" }, select: { role: true } }))?.role === "manager"; }
function manager(canManage: boolean) { if (!canManage) throw new TeamServiceError("TEAM_MANAGER_REQUIRED", 403); }
export async function canAccessTeam(id: string, userId: string, superAdmin: boolean) { try { const value = await team(id, userId, superAdmin); if (!value || value.status !== "active") return false; await integrity(value); return true; } catch { return false; } }
export async function listTeams(userId: string, superAdmin: boolean) { const db = database(); const values = superAdmin ? await db.team.findMany({ include: teamInclude() }) : (await db.teamMember.findMany({ where: { userId, status: "active" }, include: { team: { include: teamInclude() } } })).map((member: any) => member.team); const output = await Promise.all(values.filter((value: any) => value.type !== "personal").map(async (value: any) => { try { await integrity(value); return response(value, await canManageTeam(value.id, userId, superAdmin)); } catch (error) { return superAdmin && error instanceof TeamServiceError && error.code === "TEAM_INTEGRITY_UNAVAILABLE" ? { ...response(value, true), integrity: { available: false, code: error.code } } : null; } })); return output.filter(Boolean); }
export async function getTeam(id: string, userId: string, superAdmin: boolean) { manager(await canManageTeam(id, userId, superAdmin)); const value = await team(id, userId, true); return value ? response(value, true) : null; }
export async function createTeam(data: { name: string; userId: string; isSuperAdmin: boolean }) { admin(data.isSuperAdmin); const db = database(); const name = data.name.trim(); if (await db.team.findFirst({ where: { name: { equals: name, mode: "insensitive" } } })) throw new TeamServiceError("TEAM_NAME_TAKEN", 409); const value = await entitlement(); const current = await usage(); if (value.maxTeams !== null && current.teamCount >= value.maxTeams) throw new TeamServiceError("TEAM_LIMIT_REACHED", 409); const id = randomUUID(); const createdAt = new Date(); const created = await db.team.create({ data: { id, name, type: "team", createdBy: data.userId, status: "active", createdAt, provisioningSignature: teamProvisioningSignature({ id, status: "active", createdAt }) } }); return response(created, true); }
export async function updateTeam(id: string, name: string, userId: string, superAdmin: boolean) { manager(await canManageTeam(id, userId, superAdmin)); const db = database(); const value = await team(id, userId, superAdmin); if (!value) return null; const normalized = name.trim(); const duplicate = await db.team.findFirst({ where: { id: { not: id }, name: { equals: normalized, mode: "insensitive" } }, select: { id: true } }); if (duplicate) throw new TeamServiceError("TEAM_NAME_TAKEN", 409); await db.team.update({ where: { id }, data: { name: normalized } }); return getTeam(id, userId, superAdmin); }
export async function addMember(teamId: string, email: string, actorId: string, superAdmin: boolean, account: { name?: string; password?: string; role?: TeamRole } = {}) { manager(await canManageTeam(teamId, actorId, superAdmin)); const db = database(); const value = await team(teamId, actorId, superAdmin); if (!value) return null; const plan = await integrity(value); let user = await db.user.findUnique({ where: { email: email.trim().toLowerCase() } }); if (!user && (!account.name || !account.password)) throw new TeamServiceError("USER_NOT_FOUND", 404); if (user?.isSuperAdmin) throw new TeamServiceError("SUPER_ADMIN_CANNOT_BE_MEMBER", 409); const current = await usage(); if (plan.maxMembers !== null && current.memberCount >= plan.maxMembers) throw new TeamServiceError("MEMBER_LIMIT_REACHED", 409); user = user || await db.user.create({ data: { email: email.trim().toLowerCase(), name: account.name!.trim(), password: hashPassword(account.password!), isSuperAdmin: false } }); const active = await db.teamMember.findFirst({ where: { userId: user.id, status: "active" } }); if (active) throw new TeamServiceError(active.teamId === teamId ? "MEMBER_ALREADY_EXISTS" : "MEMBER_ALREADY_ASSIGNED", 409); const existing = await db.teamMember.findFirst({ where: { teamId, userId: user.id } }); const id = existing?.id || randomUUID(); const joinedAt = new Date(); const role = account.role || "staff"; const provisioningSignature = membershipProvisioningSignature({ id, teamId, userId: user.id, role, status: "active", joinedAt }); await db.teamMember.upsert({ where: { teamId_userId: { teamId, userId: user.id } }, create: { id, teamId, userId: user.id, role, status: "active", joinedAt, provisioningSignature }, update: { role, status: "active", joinedAt, provisioningSignature } }); return getTeam(teamId, actorId, superAdmin); }
export async function updateMemberRole(teamId: string, userId: string, role: TeamRole, actorId: string, superAdmin: boolean) { manager(await canManageTeam(teamId, actorId, superAdmin)); const db = database(); const member = await db.teamMember.findFirst({ where: { teamId, userId, status: "active" } }); if (!member) return null; if (member.role === "manager" && role !== "manager" && await db.teamMember.count({ where: { teamId, status: "active", role: "manager" } }) <= 1) throw new TeamServiceError("LAST_MANAGER_REQUIRED", 409); await db.teamMember.update({ where: { id: member.id }, data: { role, provisioningSignature: membershipProvisioningSignature({ ...member, role }) } }); return getTeam(teamId, actorId, superAdmin); }
export async function removeMember(teamId: string, userId: string, actorId: string, superAdmin: boolean) { manager(await canManageTeam(teamId, actorId, superAdmin)); const db = database(); const member = await db.teamMember.findFirst({ where: { teamId, userId, status: "active" } }); if (!member) return false; if (member.role === "manager" && await db.teamMember.count({ where: { teamId, status: "active", role: "manager" } }) <= 1) throw new TeamServiceError("LAST_MANAGER_REQUIRED", 409); await db.teamMember.update({ where: { id: member.id }, data: { status: "inactive", provisioningSignature: membershipProvisioningSignature({ ...member, status: "inactive" }) } }); await db.session.deleteMany({ where: { userId } }); return true; }
export async function canUserLogin(userId: string): Promise<{ allowed: true; teamId?: string } | { allowed: false; code: string }> { if (!isLocalPostgres() || !prisma) return { allowed: true }; const memberships = await (prisma as any).teamMember.findMany({ where: { userId, status: "active" } }); if (!memberships.length) return { allowed: true }; for (const membership of memberships) { const value = await team(membership.teamId, userId, false); try { if (value) { await integrity(value); return { allowed: true, teamId: membership.teamId }; } } catch (error) { if (error instanceof TeamServiceError && error.code === "TEAM_INTEGRITY_UNAVAILABLE") return { allowed: false, code: error.code }; } } return { allowed: false, code: "LICENSE_EXPIRED_OR_INVALID" }; }
